MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.09.27

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,37 +4,60 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PERL=5.20.3.1
+    - CONFIG=osx_
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "Ass2QFudRxelNFYy0hqo/vUGGV7UE/zroL0UjvBkLWrX0ADQdx5i/Ttmsy4m3j2bQBkZhRmBitKxTUl1hP9TA59yKy/9Z+/DcgEt/SvXPrrjDPKQvEHa4rOIa5E1BV4KMZHsQ6YuDJ4A8CqRVoKpKmgLAeO30NzJd9C71cetWQ5aD7nc8JzfNQAe/qyPVcSPAIADckNaK1xsPICaIGp33dlKYR5WpZUbnp0Y8pCJrH9AvSLuNOhIk7gBoA1k+hL7GbNOhl1PVO9fo+XDTW+vqmFElsS8LXhFxHhOx/4Ded7qQ70wCFLXkmK0TzO1cGtm5BWKWU0NsWJR+x5/0j/iDWn+hQg9Yd7WquHYcKNVa9XfZYnXcQDEBRwNQT3fLQ40fkH7Dl0P7xyT+HHD49sSg5bg+OMq2969z+A58vr29AI8AL+1AN+i/wb6QsLUTpMtvFcfWLWz9/RH0byIL5Nsdo36p+rCkOLXMj2bPB/pi22xQdzhITrzMCtiWpDgGoDh/IHWLZdJZ2GUWRhZqjgvV1nIRjL4n98IVBmCHIjBpsQaTJTI0359b3KdqpKTySQJkYFEgyXfz8RoZl29bGeatMvey5DXRG2iz6uQa2/O4sJrcwYFBNDzco1xu5PSEe3HVPY0PE98BQsDWjivNOJ9mSPrNGACwsladoSw1Ip3B5k="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
